name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set image tag
      run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-lab-app:${{ env.IMAGE_TAG }} ./app

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-lab-app:${{ env.IMAGE_TAG }}

    - name: Update Kubernetes Deployment
      run: |
        sed -i "s|IMAGE_TAG|${{ env.IMAGE_TAG }}|g" k8s/deployment.yml
        kubectl apply -f k8s/deployment.yml

    - name: Set kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
        export KUBECONFIG=kubeconfig